if(NOT DEFINED ST_EXECUTABLE OR NOT DEFINED MT_EXECUTABLE)
    message(FATAL_ERROR "ST_EXECUTABLE and MT_EXECUTABLE are required")
endif()

function(format_thousandths value output)
    set(sign "")
    if(value LESS 0)
        set(sign "-")
        math(EXPR value "0 - ${value}")
    endif()
    math(EXPR whole "${value} / 1000")
    math(EXPR fraction "${value} % 1000")
    set(fraction "00${fraction}")
    string(LENGTH "${fraction}" length)
    math(EXPR start "${length} - 3")
    string(SUBSTRING "${fraction}" ${start} 3 fraction)
    set(${output} "${sign}${whole}.${fraction}" PARENT_SCOPE)
endfunction()

foreach(group IN ITEMS ST1 MT1 MT4 ST4_PRIVATE)
    set(extra_args)
    set(independent_${group} 0)
    set(mode_${group} shared)
    if(group STREQUAL "ST1" OR group STREQUAL "ST4_PRIVATE")
        set(executable "${ST_EXECUTABLE}")
        set(threads_${group} 1)
        set(safe_${group} 0)
        if(group STREQUAL "ST4_PRIVATE")
            set(threads_${group} 4)
            set(independent_${group} 1)
            set(mode_${group} independent)
            set(extra_args --independent-pools)
        endif()
    else()
        set(executable "${MT_EXECUTABLE}")
        set(safe_${group} 1)
        if(group STREQUAL "MT4")
            set(threads_${group} 4)
        else()
            set(threads_${group} 1)
        endif()
    endif()
    execute_process(COMMAND "${executable}" --threads ${threads_${group}} ${extra_args}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output_${group}
        ERROR_VARIABLE errors
        TIMEOUT 90)
    message("${output_${group}}")
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${group} benchmark failed (${result}): ${errors}")
    endif()
endforeach()

message("[TABLE] Same total work per group; medians of 7 rounds; MT workers share one pool.")
message("[TABLE] scenario | variant | threads | pools | median_ms | aggregate_ns/pair | total_Mpairs/s")
foreach(scenario IN ITEMS reuse growth)
    foreach(group IN ITEMS ST1 MT1 MT4 ST4_PRIVATE)
        string(REGEX MATCH
            "RESULT ${scenario} pairs=([0-9]+) median_ns=([0-9]+) checks=([01]) thread_safe=([01]) threads=([14]) independent=([01])"
            match "${output_${group}}")
        if(NOT match)
            message(FATAL_ERROR "Missing ${scenario} result from ${group}")
        endif()
        set(pairs_${group} "${CMAKE_MATCH_1}")
        set(ns_${group} "${CMAKE_MATCH_2}")
        set(checks_${group} "${CMAKE_MATCH_3}")
        if(NOT CMAKE_MATCH_4 STREQUAL safe_${group}
            OR NOT CMAKE_MATCH_5 STREQUAL threads_${group}
            OR NOT CMAKE_MATCH_6 STREQUAL independent_${group})
            message(FATAL_ERROR "Unexpected library or thread count for ${group}")
        endif()
        if(pairs_${group} LESS_EQUAL 0 OR ns_${group} LESS_EQUAL 0)
            message(FATAL_ERROR "Invalid sample size or elapsed time")
        endif()
        if(NOT pairs_${group} STREQUAL pairs_ST1 OR NOT checks_${group} STREQUAL checks_ST1)
            message(FATAL_ERROR "Cannot compare mismatched workloads or checks settings")
        endif()
        math(EXPR ps_${group} "${ns_${group}} * 1000 / ${pairs_${group}}")
        math(EXPR microseconds "${ns_${group}} / 1000")
        math(EXPR throughput "${pairs_${group}} * 1000000 / ${ns_${group}}")
        format_thousandths(${ps_${group}} per_pair)
        format_thousandths(${microseconds} milliseconds)
        format_thousandths(${throughput} mpairs)
        if(safe_${group})
            set(variant MT)
        else()
            set(variant ST)
        endif()
        message("[TABLE] ${scenario} | ${variant} | ${threads_${group}} | ${mode_${group}} | ${milliseconds} | ${per_pair} | ${mpairs}")
    endforeach()
    message("[TABLE] ${scenario} | ST | 4 | shared | N/A | N/A | SKIP: not thread-safe")
    math(EXPR delta "${ps_MT1} - ${ps_ST1}")
    math(EXPR ratio "${ns_MT1} * 1000 / ${ns_MT4}")
    math(EXPR independent_ratio "${ns_ST1} * 1000 / ${ns_ST4_PRIVATE}")
    math(EXPR private_vs_shared "${ns_MT4} * 1000 / ${ns_ST4_PRIVATE}")
    format_thousandths(${independent_ratio} display_independent_ratio)
    format_thousandths(${private_vs_shared} display_private_vs_shared)
    format_thousandths(${delta} display_delta)
    format_thousandths(${ratio} display_ratio)
    message("[COMPARE] ${scenario}: MT(1)-ST(1)=${display_delta} ns/pair; MT(4)/MT(1) total throughput=${display_ratio}x")
    message("[COMPARE] ${scenario}: ST(4 independent)/ST(1) throughput=${display_independent_ratio}x; ST(4 independent)/MT(4 shared) throughput=${display_private_vs_shared}x")
endforeach()
message("[INFO] aggregate_ns/pair is wall time divided by total work, not per-thread latency.")
message("[PASS] Four valid groups completed; timings have no fixed pass/fail thresholds.")
